### PR TITLE
Update README URLs based on HTTP redirects

### PR DESCRIPTION
**Pull request by ReadmeCritic**
Created with https://github.com/dkhamsing/frankenstein

### GitHub Corrected URLs 
Was | Now 
--- | --- 
https://github.com/quinnliu/CallWalnutiQ | https://github.com/WalnutiQ/call_wAlnut 
`quinnliu/WalnutiQ/issues/62` | `WalnutiQ/wAlnut/issues/62`

### Other Corrected URLs 
Was | Now 
--- | --- 
http://www.youtube.com/playlist?list=PLPXsMt57rLtgddN0NQEmXP-FbF6wt2O-f | https://www.youtube.com/playlist?list=PLPXsMt57rLtgddN0NQEmXP-FbF6wt2O-f

### CODE REVIEW

**Comment by quinnliu** [comment]
@ReadmeCritic thanks!

**Comment by ReadmeCritic** [comment]
:smile:

**Comment by quinnliu** [comment]
@ReadmeCritic who are you really? like do you work at Github?

**Comment by dkhamsing** [comment]
Hi this is just a fun side project from me, not related to GitHub

**Comment by quinnliu** [comment]
you intrigue me dkhamsing

**Comment by dkhamsing** [comment]
:grin:

**Pull request merged**
